version: '3'
services:
  app:
    container_name: service      
    build:
      context: .
    network_mode: host
    stdin_open: true
    volumes:
      - /root/git/openbadges/backend/rest/public:/usr/src/app/public
